version: '2'
services:
  mysql:
    image: mysql:5.7.16
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  php:
    build: ./bin/php
    ports:
      - '80:80'
    volumes:
      - ./web:/var/www/html
    links:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    ports:
     - 8080:80
    volumes:
     - /sessions
    links:
      - mysql
volumes:
  db: